name: project cicd flow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven (ignore test failures)
      run: mvn clean install -Dmaven.test.failure.ignore=true
      working-directory: ./SimPorter

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: vodori6161/SimPorter
        tags: latest
        registry: docker.io
        dockerfile: SimPorter/Dockerfile
        context: SimPorter
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
